stages:
  # 1-minute BBO data download
  download_adr_bbo-1m:
    frozen: true
    cmd: python -m data_tools.cli.batch_download_to_parquet --schema=bbo-1m --datasets XNYS.PILLAR XNAS.ITCH ARCX.PILLAR --tickers=data/raw/adr_info.csv --tickers_columns=adr --output_dir=data/raw/adrs/bbo-1m/by_exchange --start_date=${start_date} --end_date=${end_date}
    deps:
      - data/raw/adr_info.csv
    params:
      - start_date
      - end_date
    outs:
      - data/raw/adrs/bbo-1m/by_exchange

  download_market_etf_bbo-1m:
    cmd: python -m data_tools.cli.batch_download_to_parquet --schema=bbo-1m --datasets XNYS.PILLAR XNAS.ITCH ARCX.PILLAR --tickers=data/raw/adr_info.csv --tickers_columns=market_etf_hedge --output_dir=data/raw/etfs/market/bbo-1m/by_exchange --start_date=${start_date} --end_date=${end_date}
    deps:
      - data/raw/adr_info.csv
    params:
      - start_date
      - end_date
    outs:
      - data/raw/etfs/market/bbo-1m/by_exchange

  # nbbo creation from 1min data
  create_nbbo_adr_bbo-1m:
    frozen: true
    cmd: python -m data_tools.cli.nbbo_consolidate_bbo_1m --raw_data_dir=data/raw/adrs/bbo-1m/by_exchange --output_dir=data/raw/adrs/bbo-1m/nbbo --parallel --ncores=12
    deps:
      - data/raw/adrs/bbo-1m/by_exchange
    outs:
      - data/raw/adrs/bbo-1m/nbbo

  create_nbbo_market_etf_bbo-1m:
    cmd: python -m data_tools.cli.nbbo_consolidate_bbo_1m --raw_data_dir=data/raw/etfs/market/bbo-1m/by_exchange --output_dir=data/raw/etfs/market/nbbo --parallel --ncores=12
    deps:
      - data/raw/etfs/market/bbo-1m/by_exchange
    outs:
      - data/raw/etfs/market/bbo-1m/nbbo

  # daily closing price data download
  download_adr_close:
    cmd: python src/download_bbg_daily.py data/raw/adr_info.csv data/raw/adrs/adr_PX_LAST_adjust_none.csv --tickers_columns=adr
    deps:
      - src/download_bbg_daily.py
      - data/raw/adr_info.csv
    params:
      - start_date
      - end_date
    outs:
      - data/raw/adrs/adr_PX_LAST_adjust_none.csv

  download_market_etf_close:
    cmd: python src/download_bbg_daily.py data/raw/adr_info.csv data/raw/etfs/market_etf_PX_LAST_adjust_none.csv --tickers_columns=market_etf_hedge --symbol_suffix=" US Equity"
    deps:
      - src/download_bbg_daily.py
      - data/raw/adr_info.csv
    params:
      - start_date
      - end_date
    outs:
      - data/raw/etfs/market_etf_PX_LAST_adjust_none.csv

  # downloading adr turnover

  download_adr_turnover:
    cmd: python src/download_bbg_daily.py data/raw/adr_info.csv data/raw/adrs/adr_turnover.csv --tickers_columns=adr
    deps:
      - src/download_bbg_daily.py
      - data/raw/adr_info.csv
    params:
      - start_date
      - end_date
    outs:
      - data/raw/adrs/adr_turnover.csv

  # download sector etf close prices
  download_sector_etf_close:
    cmd: python src/download_bbg_daily.py data/raw/adr_info.csv data/raw/etfs/sector_etf_PX_LAST_adjust_none.csv --tickers_columns=hedge --symbol_suffix=" US Equity"
    deps:
      - src/download_bbg_daily.py
      - data/raw/adr_info.csv
    params:
      - start_date
      - end_date
    outs:
      - data/raw/etfs/sector_etf_PX_LAST_adjust_none.csv

  download_ord_close:
    cmd: python src/download_bbg_daily.py data/raw/adr_info.csv data/raw/ordinary/ord_PX_LAST_adjust_none.csv --tickers_columns=id --include_suffix
    deps:
      - src/download_bbg_daily.py
      - data/raw/adr_info.csv
    params:
      - start_date
      - end_date
    outs:
      - data/raw/ordinary/ord_PX_LAST_adjust_none.csv

  adj_download_ord_close:
    cmd: python src/download_bbg_daily.py data/raw/adr_info.csv data/raw/ordinary/ord_PX_LAST_adjust_all.csv --tickers_columns=id --include_suffix --adjust=all
    deps:
      - src/download_bbg_daily.py
      - data/raw/adr_info.csv
    params:
      - start_date
      - end_date
    outs:
      - data/raw/ordinary/ord_PX_LAST_adjust_all.csv

  convert_ord_currency_close:
    cmd: python src/closing_domestic_prices.py
    deps:
      - src/closing_domestic_prices.py
      - data/raw/adr_info.csv
      - data/raw/ordinary/ord_PX_LAST_adjust_none.csv
      - data/raw/ordinary/ord_PX_LAST_adjust_all.csv
      - data/raw/currencies/minute_bars/GBPUSD_full_1min.txt
      - data/raw/currencies/minute_bars/EURUSD_full_1min.txt
      - data/raw/currencies/minute_bars/JPYUSD_full_1min.txt
    outs:
      - data/processed/ordinary/ord_close_to_usd_adr_PX_LAST_adjust_none.csv
      - data/processed/ordinary/ord_close_to_usd_adr_PX_LAST_adjust_all.csv

  adr_adjustments:
    cmd: python src/get_adjustments.py data/raw/adrs/adr_PX_LAST_adjust_none.csv data/processed/adrs/adr_adjustment_factors.csv --symbol_suffix=" US Equity"
    deps:
      - src/get_adjustments.py
      - data/raw/adrs/adr_PX_LAST_adjust_none.csv
    outs:
      - data/processed/adrs/adr_adjustment_factors.csv

  market_etf_adjustments:
    cmd: python src/get_adjustments.py data/raw/market_etfs/market_etf_PX_LAST_adjust_none.csv data/processed/market_etfs/market_etf_adjustment_factors.csv --symbol_suffix=" US Equity"
    deps:
      - src/get_adjustments.py
      - data/raw/market_etfs/market_etf_PX_LAST_adjust_none.csv
    outs:
      - data/processed/market_etfs/market_etf_adjustment_factors.csv

  sector_etf_adjustments:
    cmd: python src/get_adjustments.py data/raw/etfs/sector_etf_PX_LAST_adjust_none.csv data/processed/etfs/sector_etf_adjustment_factors.csv --symbol_suffix=" US Equity"
    deps:
      - src/get_adjustments.py
      - data/raw/etfs/sector_etf_PX_LAST_adjust_none.csv
    outs:
      - data/processed/etfs/sector_etf_adjustment_factors.csv

  adr_mid_at_ordinary_auction:
    cmd: python src/adr_mid_at_ordinary_auction.py
    deps:
      - src/adr_mid_at_ordinary_auction.py
      - data/raw/adrs/adr_PX_LAST_adjust_none.csv
      - data/processed/adrs/adr_adjustment_factors.csv
      - data/raw/adr_info.csv
    params:
      - start_date
      - end_date
    outs:
      - data/processed/adrs/adr_mid_at_ord_auction_adjust_all.csv
      - data/processed/adrs/adr_mid_at_ord_auction_adjust_none.csv

  usd_index_futures:
    cmd: python src/usd_index_futures.py
    deps:
      - src/usd_index_futures.py
      - data/raw/futures/minute_bars/FTUK_full_1min_continuous_ratio_adjusted.txt
      - data/raw/futures/minute_bars/FDAX_full_1min_continuous_ratio_adjusted.txt
      - data/raw/futures/minute_bars/FESX_full_1min_continuous_ratio_adjusted.txt
      - data/raw/futures/minute_bars/FXXP_full_1min_continuous_ratio_adjusted.txt
      - data/raw/futures/minute_bars/FTI_full_1min_continuous_ratio_adjusted.txt
      - data/raw/futures/minute_bars/FCE_full_1min_continuous_ratio_adjusted.txt
      - data/raw/futures/minute_bars/NIY_full_1min_continuous_ratio_adjusted.txt
      - data/raw/currencies/minute_bars/GBPUSD_full_1min.txt
      - data/raw/currencies/minute_bars/EURUSD_full_1min.txt
      - data/raw/currencies/minute_bars/JPYUSD_full_1min.txt
    outs:
      - data/processed/futures/converted_minute_bars/symbol=FTUK/FTUK_close_to_usd_1min.parquet
      - data/processed/futures/converted_minute_bars/symbol=FDAX/FDAX_close_to_usd_1min.parquet
      - data/processed/futures/converted_minute_bars/symbol=FESX/FESX_close_to_usd_1min.parquet
      - data/processed/futures/converted_minute_bars/symbol=FXXP/FXXP_close_to_usd_1min.parquet
      - data/processed/futures/converted_minute_bars/symbol=FTI/FTI_close_to_usd_1min.parquet
      - data/processed/futures/converted_minute_bars/symbol=FCE/FCE_close_to_usd_1min.parquet
      - data/processed/futures/converted_minute_bars/symbol=NIY/NIY_close_to_usd_1min.parquet

  adr_daily_fixed_time_mid:
    cmd: python -m src.adr_daily_fixed_time_mid --nbbo_dir=data/raw/adrs/bbo-1m/nbbo --time_to_save_hrs=${fixed_trade_time_hours} --time_to_save_min=${fixed_trade_time_min} --tickers=data/raw/adr_info.csv --tickers_columns=adr --output_filename=data/processed/adrs/adr_daily_fixed_time_mid.csv
    deps:
      - src/adr_daily_fixed_time_mid.py
      #- data/raw/adrs/bbo-1m/nbbo
      - data/raw/adr_info.csv
    params:
      - fixed_trade_time_hours
      - fixed_trade_time_min
    outs:
      - data/processed/adrs/adr_daily_fixed_time_mid.csv

  market_etf_daily_fixed_time_mid:
    cmd: python src/adr_daily_fixed_time_mid.py --nbbo_dir=data/raw/etfs/market/nbbo --time_to_save_hrs=${fixed_trade_time_hours} --time_to_save_min=${fixed_trade_time_min} --tickers=data/raw/adr_info.csv --tickers_columns=market_etf_hedge --output_filename=data/processed/etfs/market_etf_daily_fixed_time_mid.csv
    deps:
      - src/adr_daily_fixed_time_mid.py
      - data/raw/etfs/market/nbbo
      - data/raw/adr_info.csv
    params:
      - fixed_trade_time_hours
      - fixed_trade_time_min
    outs:
      - data/processed/etfs/market_etf_daily_fixed_time_mid.csv

  fixed_time_signal:
    cmd: python src/futures_fixed_time_signal.py

  stock_splits:
    cmd: python src/get_splits.py
    deps:
      - src/get_splits.py
      - data/raw/adr_info.csv
      - data/raw/sector_etfs.csv
    outs:
      - data/raw/all_splits.csv

  backtest_fixed_time:
    cmd: backtester_run --config_file=backtest_conifgs/single_time.yaml
    deps:
      - backtester_run
      - backtest_conifgs/single_time.yaml
      - src/backtest_strategies/single_time_ADR.py
      - data/processed/adrs/adr_daily_fixed_time_mid.csv
      - data/processed/etfs/market_etf_daily_fixed_time_mid.csv
      - data/processed/adrs/
      - data/raw/adrs/adr_PX_LAST_adjust_none.csv
      - data/raw/adrs/adr_turnover.csv
      - data/raw/all_splits.csv
      
      

  # adr_trade_price:
  #   class: HistoricalDailyCSVDataLoader
  #   csv_path: /home/pmalonis/adr_trade/data/processed/brit_adr_daily_mid_time=13:00:00.csv
  #   start_date: 2020-01-02
  # adr_signal:
  #   class: HistoricalDailyCSVDataLoader
  #   csv_path: /home/pmalonis/adr_trade/data/processed/brit_adr_futures_fixed_time_signal_time=13:00:00.csv
  #   start_date: 2020-01-02
  # turnover_df:
  #   class: HistoricalDailyCSVDataLoader
  #   csv_path: /home/pmalonis/adr_trade/data/processed/adr_turnover.csv
  #   start_date: 2020-01-02
  # adr_close:
  #   class: HistoricalDailyCSVDataLoader
  #   csv_path: /home/pmalonis/adr_trade/data/raw/adrs/adr_PX_LAST_adjust_none.csv
  #   start_date: 2020-01-02