fixed_trade_time_min: 0
fixed_trade_time_hours: 13

daily_time_for_cov_min: 0
daily_time_for_cov_hours: 13

# dates for data download
start_date: "2020-01-02"
end_date: "2025-11-07"

data_offset:
  milliseconds: 100

pred:
  lookback_days: 280

avg_dollar_volume_lookback_days: 60